=== DenisDiamantis/CodingBoocamp/Bootcamp/XML/AssignmentRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/AssignmentRules"
	xmlns:tns="http://www.example.org/AssignmentRules"
	elementFormDefault="qualified">
	
	<element name="Passenger" type="tns:Passenger"/>
	<complexType name="Passenger">		
	<sequence>
			<element name="lastName" type="tns:maxName" />
			<element name="firstName" type="tns:maxName"/>
			<element name="middleName" type="tns:maxName"/>
			<element name="email" type="string"/>
			<element name="phone" type="string"/>
			<element name="Flight" type="tns:Flight" />
		</sequence>
	</complexType>
	<complexType name="Flight">
		<sequence>
			<element name="flightNumber" type="string"/>
			<element name="operatingAirlines" type="string"/>
			<element name="arrivalCity" type="string"/>
			<element name="dateOfDeparture" type="string"/>
			<element name="estimatedDepartureTime" type="string"/>
		</sequence>
	</complexType>
	<simpleType name="maxName">
		<restriction base="string">
		<maxLength value="20"></maxLength>
		</restriction>
	</simpleType>
</schema>

=== DenisDiamantis/CodingBoocamp/Bootcamp/XML/AssignmentRules.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Passenger xmlns:tns="http://www.example.org/AssignmentRules" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/AssignmentRules AssignmentRules.xsd ">
  <tns:lastName>tns:lastName</tns:lastName>
  <tns:firstName>tns:firstName</tns:firstName>
  <tns:middleName>tns:middleName</tns:middleName>
  <tns:email>tns:email</tns:email>
  <tns:phone>tns:phone</tns:phone>
  <tns:Flight>
    <tns:flightNumber>tns:flightNumber</tns:flightNumber>
    <tns:operatingAirlines>tns:operatingAirlines</tns:operatingAirlines>
    <tns:arrivalCity>tns:arrivalCity</tns:arrivalCity>
    <tns:dateOfDeparture>tns:dateOfDeparture</tns:dateOfDeparture>
    <tns:estimatedDepartureTime>tns:estimatedDepartureTime</tns:estimatedDepartureTime>
  </tns:Flight>
</tns:Passenger>
